### ISSUE TITLE
/entrypoint.sh: 20: /entrypoint.sh: /usr/share/zookeeper/bin/zkCli.sh: not found

### ISSUE THREAD

**Issue by ihsankocak** [cd1989/high-availability#1]
by editing  your docker-compose.yml i used` docker stack deploy -c docker-compose.yml` after `patronictl remove testcluster` 3 patronies have been organized and selected and leader and others followed but, in haproxy service's logs `/entrypoint.sh: 20: /entrypoint.sh: /usr/share/zookeeper/bin/zkCli.sh: not found` appear continously. edited docker compose file is:

```
version: "3.8"
volumes:
  patroni1_metadata_data_postgres: {}
  patroni2_metadata_data_postgres: {}
  patroni3_metadata_data_postgres: {}

services:


  patroni1:
    image: zer0one/patroni:v1.5.6
    networks:
      - olap_net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      PATRONI_NAME: patroni1
      PATRONI_SCOPE:  "testcluster"
      PATRONI_ZOOKEEPER_HOSTS: "'zookeeper3:2183','zookeeper2:2182','zookeeper1:2181'"
      PATRONI_RESTAPI_USERNAME: "admin"
      PATRONI_RESTAPI_PASSWORD: "admin"
      PATRONI_RESTAPI_CONNECT_ADDRESS: "patroni1:8008"
      PATRONI_SUPERUSER_USERNAME: "postgres"
      PATRONI_SUPERUSER_PASSWORD: "postgres"
      PATRONI_REPLICATION_USERNAME: "replicator"
      PATRONI_REPLICATION_PASSWORD: "replicate"
      PATRONI_admin_PASSWORD: "admin"
      PATRONI_admin_OPTIONS:  "createdb,createrole"

    hostname: patroni1
    volumes:
      - patroni1_metadata_data_postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == analitik7.tufi.com

  patroni2:
    image: zer0one/patroni:v1.5.6
    networks:
      - olap_net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      PATRONI_NAME: patroni2
      PATRONI_SCOPE:  "testcluster"
      PATRONI_ZOOKEEPER_HOSTS: "'zookeeper3:2183','zookeeper2:2182','zookeeper1:2181'"
      PATRONI_RESTAPI_USERNAME: "admin"
      PATRONI_RESTAPI_PASSWORD: "admin"
      PATRONI_RESTAPI_CONNECT_ADDRESS: "patroni2:8008"
      PATRONI_SUPERUSER_USERNAME: "postgres"
      PATRONI_SUPERUSER_PASSWORD: "postgres"
      PATRONI_REPLICATION_USERNAME: "replicator"
      PATRONI_REPLICATION_PASSWORD: "replicate"
      PATRONI_admin_PASSWORD: "admin"
      PATRONI_admin_OPTIONS:  "createdb,createrole"
    hostname: patroni2
    volumes:
      - patroni2_metadata_data_postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == analitik8.tufi.com


  patroni3:
    image: zer0one/patroni:v1.5.6
    networks:
      - olap_net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    environment:
      PATRONI_NAME: patroni3
      PATRONI_SCOPE:  "testcluster"
      PATRONI_ZOOKEEPER_HOSTS: "'zookeeper3:2183','zookeeper2:2182','zookeeper1:2181'"
      PATRONI_RESTAPI_USERNAME: "admin"
      PATRONI_RESTAPI_PASSWORD: "admin"
      PATRONI_RESTAPI_CONNECT_ADDRESS: "patroni3:8008"
      PATRONI_SUPERUSER_USERNAME: "postgres"
      PATRONI_SUPERUSER_PASSWORD: "postgres"
      PATRONI_REPLICATION_USERNAME: "replicator"
      PATRONI_REPLICATION_PASSWORD: "replicate"
      PATRONI_admin_PASSWORD: "admin"
      PATRONI_admin_OPTIONS:  "createdb,createrole"
    hostname: patroni3
    volumes:
      - patroni3_metadata_data_postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == analitik9.tufi.com


  haproxy:
    image: zer0one/patroni:v1.5.6
    networks:
      - olap_net
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3   
    environment:
      PATRONI_SCOPE:  "testcluster"
      PATRONI_ZOOKEEPER_HOSTS: "'zookeeper3:2183','zookeeper2:2182','zookeeper1:2181'"
      PATRONI_SUPERUSER_USERNAME: "postgres"
      PATRONI_SUPERUSER_PASSWORD: "postgres"
      PATRONI_REPLICATION_USERNAME: "replicator"
      PATRONI_REPLICATION_PASSWORD: "replicate"
      PATRONI_admin_PASSWORD: "admin"
      PATRONI_admin_OPTIONS:  "createdb,createrole"
    hostname: haproxy
    ports:
      - "5432:5000"
      - "5001:5001"
      - "7000:7000"
    command: haproxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == analitik10.tufi.com


networks:
  olap_net:
    external: true

```

when i looked into the docker images by docker exec -it xxx /bin/bash there is no folder like usr/share/zookeeper. i am using image  zer0one/patroni:v1.5.6
